spring:
  application:
    name: pass_util
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dongfang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true

server:
  port: 1107

consul:
  ip: 192.168.32.15
  port: 9500