spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dongfang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
  #        #       自定义
        tags: version=1.0,author=dfzq
        healthCheckPath: /consul/health
        #       唯一标识
        instanceId: ${spring.application.name}:${server.port}
        health-check-interval: 5s
  application:
    name: consul-client

server:
  port: 1102